services:
  postgres:
    image: postgres:15-alpine
    container_name: miau_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miau_lanches_db
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: miau_backend
    restart: always
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/miau_lanches_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command:
      - sh
      - -c
      - |
        npm install
        npx prisma generate
        npx prisma migrate deploy
        npm run dev

  frontend:
    build: ./frontend
    container_name: miau_frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ['sh', '-c', 'npm install && npm run dev']
# volumes:
#   postgres_data:
